from enum import Enum


class AdvancedSearchOption(Enum):
    OPT_CONTAINS = "OPT_CONTAINS"
    OPT_SAME_LENGTH = "OPT_SAME_LENGTH"
    OPT_SAME_ABS_POSITION = "OPT_SAME_ABS_POSITION"
    OPT_CASE_INSENSITIVE = "OPT_CASE_INSENSITIVE"
    OPT_SINGLE_IS_PERFECT = "OPT_SINGLE_IS_PERFECT"
